# TCL File Generated by Component Editor 9.0sp2
# Thu Feb 25 09:41:05 EST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | oc_i2c_master "OpenCores I2C Master v1.2" v1.2
# | Richard Herveille 2010.02.25.09:41:05
# | 
# | 
# | D:/workspace/tea133/tea133_2_sw_ep3c_90sp2/ip/opencores_i2c_master/oc_i2c_master.vhd
# | 
# |    ./i2c_master_top.vhd syn
# |    ./i2c_master_byte_ctrl.vhd syn
# |    ./i2c_master_bit_ctrl.vhd syn
# |    ./oc_i2c_master.vhd syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module oc_i2c_master
# | 
set_module_property DESCRIPTION ""
set_module_property NAME oc_i2c_master
set_module_property VERSION 1.2
set_module_property INTERNAL false
set_module_property GROUP "Peripherals/Microcontroller Peripherals"
set_module_property AUTHOR "Richard Herveille"
set_module_property DISPLAY_NAME "OpenCores I2C Master v1.2"
set_module_property LIBRARIES {ieee.std_logic_1164.all ieee.std_logic_arith.all std.standard.all}
set_module_property DATASHEET_URL http://www.opencores.com/project,i2c
set_module_property TOP_LEVEL_HDL_FILE oc_i2c_master.vhd
set_module_property TOP_LEVEL_HDL_MODULE oc_i2c_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file i2c_master_top.vhd SYNTHESIS
add_file i2c_master_byte_ctrl.vhd SYNTHESIS
add_file i2c_master_bit_ctrl.vhd SYNTHESIS
add_file oc_i2c_master.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point global_signals_export
# | 
add_interface global_signals_export conduit start

set_interface_property global_signals_export ENABLED true

add_interface_port global_signals_export scl_pad_io export Bidir 1
add_interface_port global_signals_export sda_pad_io export Bidir 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_clock
# | 
add_interface avalon_slave_0_clock clock end
set_interface_property avalon_slave_0_clock ptfSchematicName ""

set_interface_property avalon_slave_0_clock ENABLED true

add_interface_port avalon_slave_0_clock wb_clk_i clk Input 1
add_interface_port avalon_slave_0_clock wb_rst_i reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice true
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK avalon_slave_0_clock
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 wb_ack_o waitrequest_n Output 1
add_interface_port avalon_slave_0 wb_adr_i address Input 3
add_interface_port avalon_slave_0 wb_dat_i writedata Input 32
add_interface_port avalon_slave_0 wb_dat_o readdata Output 32
add_interface_port avalon_slave_0 wb_stb_i chipselect Input 1
add_interface_port avalon_slave_0 wb_we_i write Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_irq
# | 
add_interface avalon_slave_0_irq interrupt end
set_interface_property avalon_slave_0_irq associatedAddressablePoint avalon_slave_0

set_interface_property avalon_slave_0_irq ASSOCIATED_CLOCK avalon_slave_0_clock
set_interface_property avalon_slave_0_irq ENABLED true

add_interface_port avalon_slave_0_irq wb_inta_o irq Output 1
# | 
# +-----------------------------------
